config/routes.rb
Rails.application.routes.draw do
  get 'movies/new'
  get 'movies/create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :lists do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: :destroy
  # Defines the root path route ("/")
  root to: "lists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates_uniqueness_of :movie_id, scope: :list_id, message: "You have already selected this movie"
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list_id = params[:list_id]
    if @bookmark.save
      redirect_to @bookmark.list, notice: 'Bookmark created.'
    else
      render :new
    end
  end

  def destroy
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = @list.bookmarks
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to list_path(@list)
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    @list.update(list_params)
    redirect_to list_path(@list)
  end

  def destroy
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @movie = Movie.new
  end

  def create
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/create.html.erb
<h1>Bookmarks#create</h1>
<p>Find me in app/views/bookmarks/create.html.erb</p>

app/views/bookmarks/destroy.html.erb
<h1>Bookmarks#destroy</h1>
<p>Find me in app/views/bookmarks/destroy.html.erb</p>

app/views/bookmarks/new.html.erb
<div class="container">
<h3>Add Bookmarks</h3>
<%= simple_form_for [@list, @bookmark] do |f|%>
<%= f.input :comment %>
<%= f.association :movie %>
<%= f.submit %>
<% end %>
<hr>
<%= link_to "Back", lists_path%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/destroy.html.erb
<h1>Lists#destroy</h1>
<p>Find me in app/views/lists/destroy.html.erb</p>

app/views/lists/edit.html.erb
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.submit "Save" %>
<% end %>

app/views/lists/index.html.erb
<h1>My List</h1>
<ul>
  <% @lists.each do |list| %>
    <li><%= link_to list.name, list_path(list)  %> <%=link_to 'Edit List', edit_list_path(list)%> </li>
  <% end %>
</ul>
<p><%= link_to 'Add List', new_list_path(@list) %></p>

app/views/lists/new.html.erb
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.submit "Save" %>
<% end %>
<%= link_to "Back", lists_path%>

app/views/lists/show.html.erb
<h2><%= @list.name %></h2>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/background.png);">
  <div class="container">
    <h1>Le Wagon brings <strong>tech skills</strong> to <strong>creative people</strong>!</h1>
    <p>Change your life and learn to code at one of our campuses around the world.</p>
    <a class="btn btn-flat" href="#">Apply now</a>
  </div>
</div>

<% @bookmarks.each do |bookmark|%>
<p><%= bookmark.comment %></p>
<p><%= bookmark.movie.title %></p>
<p><%= image_tag bookmark.movie.poster_url, width:100, height:100  %></p>
<%end%>

<hr>

<hr>
<p><%= link_to 'Back to list', lists_path(@lists) %></p>
<p><%=link_to "Add Bookmark", new_list_bookmark_path(@list)%></p>

app/views/lists/update.html.erb
<h1>Lists#update</h1>
<p>Find me in app/views/lists/update.html.erb</p>

app/views/movies/create.html.erb
<h1>Movies#create</h1>
<p>Find me in app/views/movies/create.html.erb</p>

app/views/movies/new.html.erb
<h1>Movies#new</h1>
<p>Find me in app/views/movies/new.html.erb</p>